import React, { useState } from 'react';
import './JobList.scss';
import JobCard from './JobCard'; 

// 더미 데이터
export const dummyData = [
    {
      id: 1,
      work_place_name: '넥스트러너스',
      title: '저같은 교육자 뽑아요',
      work_address: '서울 강북구',
      other_conditions: '60대 이상 가능, 상주 인력 환영',
      deadline_at: '2025-06-25',
      job_category: '교육',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '운전면허 소지자,경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 2,
      work_place_name: 'ABC Tech',
      title: '프론트엔드 개발자 채용',
      work_address: '서울 강남구',
      other_conditions: '경력 3년 이상',
      deadline_at: '2025-05-01',
      job_category: 'IT',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '',
      recruit_period_end: '',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: true,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 3,
      work_place_name: '부산 IT',
      title: '백엔드 개발자 채용',
      work_address: '부산 해운대구',
      other_conditions: 'Node.js 가능자 우대',
      deadline_at: '2025-06-30',
      job_category: 'IT',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-06-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 4,
      work_place_name: '인천 스타트업',
      title: '디자이너 채용',
      work_address: '인천 부평구',
      other_conditions: '포토샵 가능자',
      deadline_at: '2025-07-15',
      job_category: '디자인',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 5,
      work_place_name: '광주 스마트공장',
      title: '기계 설계',
      work_address: '광주 광산구',
      other_conditions: '기계 CAD 가능자',
      deadline_at: '2025-08-01',
      job_category: '제조',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 6,
      work_place_name: '제주리조트',
      title: '프론트 직원 채용',
      work_address: '제주 서귀포시',
      other_conditions: '호텔 경험자 우대',
      deadline_at: '2025-09-10',
      job_category: '서비스',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 7,
      work_place_name: '서울 헬스케어',
      title: '간호사 모집',
      work_address: '서울 송파구',
      other_conditions: '자격증 소지자',
      deadline_at: '2025-09-30',
      job_category: '의료',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 8,
      work_place_name: '서울문화센터',
      title: '문화 기획자',
      work_address: '서울 종로구',
      other_conditions: '문화 행사 기획 경험',
      deadline_at: '2025-10-05',
      job_category: '기획',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 9,
      work_place_name: '부산 물류센터',
      title: '물류 관리자',
      work_address: '부산 사하구',
      other_conditions: '지게차 가능자 우대',
      deadline_at: '2025-08-20',
      job_category: '물류',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 10,
      work_place_name: '부산 스타트업',
      title: '프론트엔드 개발자',
      work_address: '부산 금정구',
      other_conditions: 'React 가능자',
      deadline_at: '2025-07-25',
      job_category: 'IT',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 11,
      work_place_name: '인천 물류회사',
      title: '배송 기사',
      work_address: '인천 연수구',
      other_conditions: '운전면허 필수',
      deadline_at: '2025-09-01',
      job_category: '운송',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 12,
      work_place_name: '인천 문화센터',
      title: '이벤트 운영',
      work_address: '인천 중구',
      other_conditions: '행사 진행 경험자',
      deadline_at: '2025-10-01',
      job_category: '기획',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 13,
      work_place_name: '광주 테크',
      title: '제품 디자이너',
      work_address: '광주 서구',
      other_conditions: 'UX/UI 디자인 경험자',
      deadline_at: '2025-08-15',
      job_category: '디자인',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: true,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 14,
      work_place_name: '광주 교육기관',
      title: '보조 강사',
      work_address: '광주 남구',
      other_conditions: '교육 경력자 우대',
      deadline_at: '2025-09-05',
      job_category: '교육',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 15,
      work_place_name: '제주 자연농장',
      title: '농장 관리직',
      work_address: '제주 제주시',
      other_conditions: '농업 경험자 우대',
      deadline_at: '2025-07-20',
      job_category: '농업',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    {
      id: 16,
      work_place_name: '제주 스타트업',
      title: '웹디자이너',
      work_address: '제주 제주시',
      other_conditions: 'Photoshop, Figma 사용 가능자',
      deadline_at: '2025-08-28',
      job_category: '디자인',
      salary: 10000,
      payment_method: '월급',
      description: '상세 내용이 여기에 들어갑니다.',
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-12-31',
      education: '학력무관',
      recruit_number: 1,
      preferred_conditions: '경력자 우대',
      employment_type: '정규직',
      benefits: '병가, 유급 휴가, 가족상 휴가',
      career: '경력',
      work_duration: '1년 이상',
      work_days: '월-금',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
      is_always_recruiting: false,
      company_users_id: 1,
      company_id: 1
    },
    // 더미 데이터 추가...
  ];

const JobList = ({ jobs = [] }) => {
const [isBookmarked, setIsBookmarked] = useState({});

const toggleBookmark = (id) => {
  setIsBookmarked((prev) => ({
    ...prev,
    [id]: !prev[id]
  }));
};

  // API가 준비될 때까지 더미 데이터 사용
  const data = jobs.length ? jobs : dummyData;

  return (
        <div className="job-list">
        {data.map((job) => (
          <JobCard
            key={job.id}
            job={job}
            isBookmarked={isBookmarked[job.id]}
            toggleBookmark={toggleBookmark}
          />
        ))}
        </div>
  );
};

export default JobList;