export const Bookmark = [
  {
    id: 10,
    user_id: 1,
    job_posting_id: {
      id: 1,
      title: '울퉁불퉁 멋진 몸매에',
      company_users_id: 2,
      company_id: 1,
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-06-30',
      is_always_recruiting: false,
      education: '대졸',
      recruit_number: 3,
      benefits: '병가, 유급 휴가, 가족상 휴가',
      preferred_conditions: '동종업계 경력자, 운전면허 소지자',
      other_conditions: '상시 모집, 초보 가능',
      work_address: '서울시 강남구 역삼동 123-45',
      work_place_name: 'ABC Tech Center',
      payment_method: '월급',
      job_category: 'IT·인터넷',
      work_duration: '1년 이상',
      career: '경력',
      employment_type: '정규직',
      salary: 5000,
      deadline_at: '2025-12-31',
      work_days: '월-금',
      description: '채용 공고 상세 내용',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
    },
    created_at: '2025-04-05T10:00:00Z',
  },
  {
    id: 11,
    user_id: 1,
    job_posting_id: {
      id: 2,
      title: '빨간 옷을 입구',
      company_users_id: 2,
      company_id: 2,
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-06-30',
      is_always_recruiting: false,
      education: '대졸',
      recruit_number: 3,
      benefits: '병가, 유급 휴가, 가족상 휴가',
      preferred_conditions: '동종업계 경력자, 운전면허 소지자',
      other_conditions: '상시 모집, 초보 가능',
      work_address: '서울시 강남구 역삼동 123-45',
      work_place_name: 'ABC Tech Center',
      payment_method: '월급',
      job_category: 'IT·인터넷',
      work_duration: '1년 이상',
      career: '경력',
      employment_type: '정규직',
      salary: 5000,
      deadline_at: '2025-12-31',
      work_days: '월-금',
      description: '채용 공고 상세 내용',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
    },
    created_at: '2025-04-05T10:00:00Z',
  },
  {
    id: 12,
    user_id: 1,
    job_posting_id: {
      id: 3,
      title: '새콤달콤 냄새 풍기는',
      company_users_id: 2,
      company_id: 11,
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-06-30',
      is_always_recruiting: false,
      education: '대졸',
      recruit_number: 4,
      benefits: '병가, 유급 휴가, 가족상 휴가',
      preferred_conditions: '동종업계 경력자, 운전면허 소지자',
      other_conditions: '상시 모집, 초보 가능',
      work_address: '서울시 강남구 역삼동 123-45',
      work_place_name: 'ABC Tech Center',
      payment_method: '월급',
      job_category: 'IT·인터넷',
      work_duration: '1년 이상',
      career: '경력',
      employment_type: '정규직',
      salary: 5000,
      deadline_at: '2025-12-31',
      work_days: '월-금',
      description: '채용 공고 상세 내용',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
    },
    created_at: '2025-04-05T10:00:00Z',
  },
  {
    id: 13,
    user_id: 1,
    job_posting_id: {
      id: 4,
      title: '멋쟁이 토마토',
      company_users_id: 2,
      company_id: 18,
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-06-30',
      is_always_recruiting: false,
      education: '대졸',
      recruit_number: 3,
      benefits: '병가, 유급 휴가, 가족상 휴가',
      preferred_conditions: '동종업계 경력자, 운전면허 소지자',
      other_conditions: '상시 모집, 초보 가능',
      work_address: '서울시 강남구 역삼동 123-45',
      work_place_name: 'ABC Tech Center',
      payment_method: '월급',
      job_category: 'IT·인터넷',
      work_duration: '1년 이상',
      career: '경력',
      employment_type: '정규직',
      salary: 5000,
      deadline_at: '2025-12-31',
      work_days: '월-금',
      description: '채용 공고 상세 내용',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
    },
    created_at: '2025-04-05T10:00:00Z',
  },
  {
    id: 14,
    user_id: 1,
    job_posting_id: {
      id: 1,
      title: '토마토가 젤루 조아',
      company_users_id: 2,
      company_id: 19,
      recruit_period_start: '2025-01-01',
      recruit_period_end: '2025-06-30',
      is_always_recruiting: false,
      education: '대졸',
      recruit_number: 3,
      benefits: '병가, 유급 휴가, 가족상 휴가',
      preferred_conditions: '동종업계 경력자, 운전면허 소지자',
      other_conditions: '상시 모집, 초보 가능',
      work_address: '서울시 강남구 역삼동 123-45',
      work_place_name: 'ABC Tech Center',
      payment_method: '월급',
      job_category: 'IT·인터넷',
      work_duration: '1년 이상',
      career: '경력',
      employment_type: '정규직',
      salary: 5000,
      deadline_at: '2025-12-31',
      work_days: '월-금',
      description: '채용 공고 상세 내용',
      created_at: '2025-04-05T10:00:00Z',
      updated_at: '2025-04-05T10:00:00Z',
    },
    created_at: '2025-04-05T10:00:00Z',
  },
];
