name: Deploy To Dev NCP

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm install

      #      - name: .env 파일 생성
      #        run: |
      #          echo "VITE_KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
      #          echo "VITE_KAKAO_REDIRECT_URI=${{ secrets.DEV_KAKAO_REDIRECT_URI }}" >> .env
      #          echo "VITE_KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
      #          echo "VITE_NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
      #          echo "VITE_NAVER_REDIRECT_URI=${{ secrets.DEV_NAVER_REDIRECT_URI }}" >> .env
      #          echo "VITE_NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env

      - name: 빌드
        run: npm run build

      - name: Object Storage 기존 파일들 삭제
        run: |
          s3cmd del --recursive --force s3://${{ secrets.NCP_BUCKET }}/

      - name: Object Storage 새 파일 등록
        run: |
          s3cmd sync dist/ s3://${{ secrets.NCP_BUCKET }}/ --exclude '*.DS_Store'  # dist 폴더 업로드
